openapi: 3.0.0
info:
  title: カラフルモアイAPI
  description: カラフルなモアイのリストを管理するAPI。
  version: 1.0.0
paths:
  /api/colorful-moai:
    get:
      summary: カラフルモアイ一覧を取得
      operationId: getColorfulMoai
      tags:
        - colorful-moai
      responses:
        "200":
          description: カラフルモアイの一覧
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetColorfulMoaiResponse"
    post:
      summary: 新しいカラフルモアイを追加
      operationId: addColorfulMoai
      tags:
        - colorful-moai
      requestBody:
        description: 追加するカラフルモアイ。
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddColorfulMoaiBody"
      responses:
        "200":
          description: 更新されたカラフルモアイの一覧
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddColorfulMoaiResponse"
components:
  schemas:
    AddColorfulMoaiBody:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "黄モアイ"
    AddColorfulMoaiResponse:
      type: array
      items:
        type: string
      example: ["赤モアイ", "緑モアイ", "青モアイ", "黄モアイ"]
    GetColorfulMoaiResponse:
      type: array
      items:
        type: string
      example: ["赤モアイ", "緑モアイ", "青モアイ"]
